# Generated by Django 6.0.1 on 2026-03-06 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_habit_end_date_habit_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст цели')),
                ('goal_type', models.CharField(choices=[('once', '✔️ Однократная'), ('ongoing', '🕑 Постоянная')], default='once', max_length=10, verbose_name='Тип цели')),
                ('week_start', models.DateField(verbose_name='Неделя (понедельник)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('is_carried_over', models.BooleanField(default=False, verbose_name='Перенесена на след. неделю')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цель недели',
                'verbose_name_plural': 'Цели недели',
                'ordering': ['week_start', '-created_at'],
            },
        ),
    ]
