# Generated by Django 6.0.3 on 2026-03-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_weeklygoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklygoal',
            name='goal_type',
        ),
    ]
