# Generated by Django 6.0.3 on 2026-03-21 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_remove_weeklygoal_goal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц (1-12)')),
                ('text', models.TextField(verbose_name='Текст цели')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('carried_over', models.BooleanField(default=False, verbose_name='Перенесена на следующий месяц')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цель месяца',
                'verbose_name_plural': 'Цели месяцев',
                'ordering': ['year', 'month', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц (1-12)')),
                ('text', models.TextField(blank=True, verbose_name='Отчёт за месяц')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчёт за месяц',
                'verbose_name_plural': 'Отчёты за месяц',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='YearlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('text', models.TextField(verbose_name='Текст цели')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Годовая цель',
                'verbose_name_plural': 'Годовые цели',
                'ordering': ['year', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='YearlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('text', models.TextField(blank=True, verbose_name='Годовой отчёт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Годовой отчёт',
                'verbose_name_plural': 'Годовые отчёты',
                'ordering': ['-year'],
            },
        ),
    ]
